blank_issues_enabled: false
contact_links:
  - name: ⚠️ Extension/source issue
    url: https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose
    about: Issues and requests for extensions and sources should be opened in the tachiyomi-extensions repository instead
  - name: 📦 Tachiyomi extensions
    url: https://tachiyomi.org/extensions
    about: List of all available extensions with download links
  - name: 🖥️ Tachiyomi website
    url: https://tachiyomi.org/help/
    about: Guides, troubleshooting, and answers to common questions
